<?php
	include_once('api.php');
	$api = new Api();	

	/*for($i = 0; $i < 10; $i++){
		$api->post_new_task("New post: ".(string)$i, "This is a post generated by my loop. it has number: ".(string)$i, "31/03/2018 12:00 am");	
	}*/

	$url = $api->post_new_task($title, $desc, $deadline)
?>